"""Add image path column to clothing piece

Revision ID: 2ef084b43a2f
Revises: 2786e771c6f8
Create Date: 2025-08-04 19:15:05.933914

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ef084b43a2f"
down_revision: Union[str, Sequence[str], None] = "2786e771c6f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clothing_pieces", sa.Column("image_path", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clothing_pieces", "image_path")
    # ### end Alembic commands ###
