"""make choices data user specific

Revision ID: 416275146e2e
Revises: 2ef084b43a2f
Create Date: 2025-08-15 21:50:30.917232

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "416275146e2e"
down_revision: Union[str, Sequence[str], None] = "2ef084b43a2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clothing_piece_fabric", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "clothing_piece_fabric", "users", ["user_id"], ["id"], ondelete="cascade"
    )
    op.add_column("clothing_piece_size", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "clothing_piece_size", "users", ["user_id"], ["id"], ondelete="cascade"
    )
    op.add_column("clothing_piece_status", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "clothing_piece_status", "users", ["user_id"], ["id"], ondelete="cascade"
    )
    op.add_column("colors", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "colors", "users", ["user_id"], ["id"], ondelete="cascade")
    op.add_column("weather_seasons", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "weather_seasons", "users", ["user_id"], ["id"], ondelete="cascade")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weather_seasons", type_="foreignkey")  # type: ignore
    op.drop_column("weather_seasons", "user_id")
    op.drop_constraint(None, "colors", type_="foreignkey")  # type: ignore
    op.drop_column("colors", "user_id")
    op.drop_constraint(None, "clothing_piece_status", type_="foreignkey")  # type: ignore
    op.drop_column("clothing_piece_status", "user_id")
    op.drop_constraint(None, "clothing_piece_size", type_="foreignkey")  # type: ignore
    op.drop_column("clothing_piece_size", "user_id")
    op.drop_constraint(None, "clothing_piece_fabric", type_="foreignkey")  # type: ignore
    op.drop_column("clothing_piece_fabric", "user_id")
    # ### end Alembic commands ###
